services:
  grafana:
    image: grafana/grafana-oss:11.4.0
    container_name: streamlake-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=https://github.com/michelin/snowflake-grafana-datasource/releases/latest/download/snowflake-grafana-datasource.zip;michelin-snowflake-datasource
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=michelin-snowflake-datasource
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: